Repository oz-collabo-project-team-03/AI_Teacher, pull requests merged in 2024-12, with the labels that each got.

#69 [Feature/login] 엔드포인트 생성
  generate_data/student.py
  generate_data/studygroup.py
  generate_data/teacher.py
  src/app/router/v1/user.py
  src/app/v1/auth/schema/responseDto.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/service/user_service.py
  src/config/database/postgresql.py
  src/main.py
Labels: enhancement

#70 [Feature/login]에러 문구 제거
  src/app/common/utils/dependency.py
  src/app/router/v1/user.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/service/user_service.py
Labels: bug

#71 [Fix/Chat] Fix chat
  poetry.lock
  pyproject.toml
  src/app/router/v1/chat.py
  src/app/v1/chat/entity/participant.py
  src/app/v1/chat/entity/room.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/user/entity/user.py
Labels: bug

#72 [Feature/login]임시 데이터 생성 코드 추가
  generate_data/student.py
  generate_data/teacher.py
  migrations/env.py
  src/main.py
Labels: enhancement

#77 [Feature/login]소셜로그인 기능 추가, access token 시간 변경
  src/app/common/utils/redis_utils.py
  src/app/router/v1/auth.py
  src/app/v1/auth/repository/auth_repository.py
  src/app/v1/auth/repository/oauth_repository.py
  src/app/v1/auth/schema/responseDto.py
  src/app/v1/auth/service/auth_service.py
  src/app/v1/auth/service/kakao_service.py
  src/app/v1/auth/service/oauth_service.py
  src/app/v1/user/service/user_service.py
  src/main.py
Labels: enhancement

#79 [Feature/Chat] many change
  src/app/common/utils/websocket_manager.py
  src/app/router/__init__.py
  src/app/router/v1/teacher.py
  src/app/router/v1/websocket.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/repository/room_repository.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/chat/service/chat.py
  src/main.py
Labels: bug, enhancement

#80 [Feature/Chat] change Time format
  src/app/v1/chat/repository/room_repository.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/chat/service/chat.py
Labels: enhancement

#81 Add Orgin, Arrange Import
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/schema/room_response.py
  src/main.py
Labels: enhancement

#83 [Feature/Chat] Add help_room Endpoint
  src/app/router/__init__.py
  src/app/router/v1/chat.py
  src/app/router/v1/teacher.py
  src/app/router/v1/websocket.py
  src/app/v1/chat/repository/room_repository.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/chat/service/room_service.py
Labels: enhancement

#84 [Feature] Add health check Logic
  src/main.py
Labels: enhancement

#94 [Feature/login]소셜로그인 기능 추가
  src/app/router/v1/auth.py
  src/app/v1/auth/repository/oauth_repository.py
  src/app/v1/auth/schema/requestDto.py
  src/app/v1/auth/schema/responseDto.py
  src/app/v1/auth/service/oauth_service.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/schema/responseDto.py
Labels: enhancement

#116 [Feature/users]소셜로그인 회원정보추가 엔드포인트 수정
  src/app/common/utils/redis_utils.py
  src/app/common/utils/security.py
  src/app/router/v1/auth.py
  src/app/v1/auth/repository/oauth_repository.py
  src/app/v1/auth/service/oauth_service.py
Labels: enhancement

#192 Fix README change height
  README.md
Labels: enhancement
