Repository oz-collabo-project-team-03/AI_Teacher, pull requests merged in 2024-11, with the labels that each got.

#23 [Feature/post] 타입힌트, import 리팩토링
  src/app/router/__init__.py
  src/app/v1/post/schema/post.py
  src/main.py
Labels: enhancement

#29 [Feature/chat] Add Chat Entities, Fix regex in main.py, Arrange Directory
  .gitignore
  src/app/v1/auth/entity/__init__.py
  src/app/v1/chat/entity/__init__.py
  src/app/v1/chat/entity/chat_participant.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/entity/room.py
  src/main.py
Labels: enhancement

#30 [Fix/Feature] Arrange user, chat & Fix/Feature check.bat for windows and Add Linux
  src/app/v1/chat/entity/message.py
  src/app/v1/user/entity/student.py
  src/app/v1/user/entity/study_group.py
  src/app/v1/user/entity/teacher.py
  src/app/v1/user/entity/user.py
  src/main.py
Labels: bug, enhancement

#31 [Feature/chat] Add Field in room entity
  src/app/v1/chat/entity/room.py
Labels: enhancement

#32 [Feature/chat] Add Chat Entity & Chat Test & Refactoring consts, main, etc
  src/app/common/utils/consts.py
  src/app/v1/chat/entity/chat_participant.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/entity/room.py
  src/main.py
  tests/chats/__init__.py
  tests/chats/test_chat_model.py
  tests/comments/test_comment_model.py
  tests/users/test_async_user_model.py
  tests/users/test_user_model.py
Labels: bug, enhancement

#33 [Feature/chat] Change Entity
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/entity/room.py
Labels: enhancement

#34 [Feature/login]회원가입, 로그인 기능 생성
  .github/workflows/CI.yml
  .gitignore
  alembic.ini
  poetry.lock
  pyproject.toml
  src/app/common/utils/consts.py
  src/app/common/utils/dependency.py
  src/app/common/utils/redis.py
  src/app/common/utils/security.py
  src/app/common/utils/send_email.py
  src/app/common/utils/verify_password.py
  src/app/router/__init__.py
  src/app/router/v1/auth.py
  src/app/router/v1/user.py
  src/app/v1/auth/schema/requestDto.py
  src/app/v1/auth/schema/responseDto.py
  src/app/v1/auth/service/auth_service.py
  src/app/v1/recomment/enitity/__init__.py
  src/app/v1/recomment/enitity/recomment.py
  src/app/v1/recomment/entity/__init__.py
  src/app/v1/recomment/entity/recomment.py
  src/app/v1/recomment/entity/recomment_tag.py
  src/app/v1/user/entity/student.py
  src/app/v1/user/entity/study_group.py
  src/app/v1/user/entity/teacher.py
  src/app/v1/user/entity/user.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/schema/responseDto.py
  src/app/v1/user/service/user_service.py
  src/config/database/database_models.py
  src/main.py
  tests/chats/test_chat_model.py
Labels: enhancement

#36 [Feature/login]GradeNumber Enum 삭제
  .gitignore
  alembic.ini
  migrations/versions/2024_11_23_0250-715b09667efd_initialize_table.py
  src/app/common/models/tag.py
  src/app/common/utils/consts.py
  src/app/common/utils/dependency.py
  src/app/router/v1/user.py
  src/app/v1/recomment/entity/recomment.py
  src/app/v1/user/entity/student.py
  src/app/v1/user/entity/user.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/service/user_service.py
  src/config/database/database_models.py
  tests/chats/test_chat_model.py
Labels: enhancement

#37 [Feature/login]회원가입 수정
  alembic.ini
  migrations/versions/2024_11_23_1533-ef31195d03ca_initialize_table.py
  poetry.lock
  pyproject.toml
  src/app/common/models/tag.py
  src/app/common/utils/consts.py
  src/app/router/v1/auth.py
  src/app/router/v1/user.py
  src/app/v1/auth/schema/requestDto.py
  src/app/v1/auth/schema/responseDto.py
  src/app/v1/auth/service/auth_service.py
  src/app/v1/user/entity/organization.py
  src/app/v1/user/entity/student.py
  src/app/v1/user/entity/teacher.py
  src/app/v1/user/entity/user.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/service/user_service.py
Labels: enhancement

#38 [Feature/DB] Change DB Connection Setting
  .gitignore
  migrations/env.py
  tests/chats/db_test.py
Labels: enhancement

#39 [Feature/DB] Change DB Connection Setting
  src/config/database/postgresql.py
  tests/chats/db_engine.py
Labels: enhancement

#51 Fix/User Email send Function
  poetry.lock
  src/app/common/utils/redis.py
  src/app/common/utils/send_email.py
Labels: enhancement

#54 Feature/Chat many change
  src/app/common/factory.py
  src/app/router/__init__.py
  src/app/router/v1/chat.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/entity/participant.py
  src/app/v1/chat/entity/room.py
  src/app/v1/chat/repository/room_repository.py
  src/app/v1/chat/schema/room_request.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/chat/service/room_service.py
  src/app/v1/recomment/entity/recomment.py
  src/app/v1/user/entity/user.py
  src/config/database/database_models.py
  src/config/database/postgresql.py
  src/config/database/redis.py
  src/main.py
Labels: documentation

#55 Feature/Chat Websocket and Entity
  src/app/router/v1/websocket.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/service/room_service.py
Labels: enhancement

#57 [Feature/login]User entity 수정 및 api 추가생성
  docker-compose.yaml
  src/app/common/factory.py
  src/app/common/utils/verify_password.py
  src/app/router/__init__.py
  src/app/router/v1/auth.py
  src/app/router/v1/chat.py
  src/app/router/v1/websocket.py
  src/app/v1/chat/entity/participant.py
  src/app/v1/chat/entity/room.py
  src/app/v1/chat/repository/room_repository.py
  src/app/v1/chat/schema/room_response.py
  src/app/v1/chat/service/room_service.py
  src/app/v1/user/entity/user.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/schema/responseDto.py
  src/app/v1/user/service/user_service.py
  src/config/database/database_models.py
  src/main.py
Labels: enhancement

#63 [Feature/Chat] Change Message Entity to MongoDB from RDBMS, etc
  poetry.lock
  pyproject.toml
  src/app/common/factory.py
  src/app/router/v1/chat.py
  src/app/router/v1/websocket.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/entity/participant.py
  src/app/v1/chat/service/room_service.py
  src/config/database/mongo.py
  src/config/database/redis.py
  src/config/logging.py
  src/config/settings.py
Labels: bug, enhancement

#64 [Feature/login]선생님 조회, 학생 최초 로그인 시 선생님 선택 엔드포인트 추가
  src/app/common/utils/dependency.py
  src/app/router/v1/auth.py
  src/app/router/v1/user.py
  src/app/v1/user/entity/teacher.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/schema/responseDto.py
  src/app/v1/user/service/user_service.py
Labels: enhancement

#65 [Fix/Chat] Fix Message
  src/app/v1/chat/entity/message.py
Labels: enhancement

#68 [Feature/login]엔드포인트 추가
  poetry.lock
  src/app/common/factory.py
  src/app/common/utils/image.py
  src/app/common/utils/security.py
  src/app/router/v1/chat.py
  src/app/router/v1/user.py
  src/app/router/v1/websocket.py
  src/app/v1/chat/entity/message.py
  src/app/v1/chat/service/room_service.py
  src/app/v1/user/repository/user_repository.py
  src/app/v1/user/schema/requestDto.py
  src/app/v1/user/schema/responseDto.py
  src/app/v1/user/service/user_service.py
  src/config/database/mongo.py
Labels: enhancement
